// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVUHXAACcLQCUCXJC1FDxy-4gIpZIpUrA',
    appId: '1:725247131174:web:6f3f55688bd9f8ddb8f0e7',
    messagingSenderId: '725247131174',
    projectId: 'texops-2e8cf',
    authDomain: 'texops-2e8cf.firebaseapp.com',
    storageBucket: 'texops-2e8cf.firebasestorage.app',
    measurementId: 'G-ZLM4TNRFEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzkjLgVHQmlVB-dj8aA4kh65B0w0_rzGg',
    appId: '1:725247131174:android:21653e35871c5ca7b8f0e7',
    messagingSenderId: '725247131174',
    projectId: 'texops-2e8cf',
    storageBucket: 'texops-2e8cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSchJrNAuIkZ4SVC0dxD6J0yXdmmIJokg',
    appId: '1:725247131174:ios:61a73af5272d68b7b8f0e7',
    messagingSenderId: '725247131174',
    projectId: 'texops-2e8cf',
    storageBucket: 'texops-2e8cf.firebasestorage.app',
    iosBundleId: 'com.example.texops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSchJrNAuIkZ4SVC0dxD6J0yXdmmIJokg',
    appId: '1:725247131174:ios:61a73af5272d68b7b8f0e7',
    messagingSenderId: '725247131174',
    projectId: 'texops-2e8cf',
    storageBucket: 'texops-2e8cf.firebasestorage.app',
    iosBundleId: 'com.example.texops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVUHXAACcLQCUCXJC1FDxy-4gIpZIpUrA',
    appId: '1:725247131174:web:e0823f19e6656192b8f0e7',
    messagingSenderId: '725247131174',
    projectId: 'texops-2e8cf',
    authDomain: 'texops-2e8cf.firebaseapp.com',
    storageBucket: 'texops-2e8cf.firebasestorage.app',
    measurementId: 'G-RF29KB5B3M',
  );
}
